name: 'GitDiff Docker push'
description: 'Check git diff & Push docker images'
inputs:
  github-token:
    required: false
  registry:
    required: false
    default: 'registry.hub.docker.com'
  username:
    required: false
  password:
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
